version: "3"

services:
  web:
    env_file:
      - ./.env
    restart: always
    build:
      context: "./Docker_Web"
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  db:
    env_file:
      - ./.env
    restart: always
    image: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - lamp-docker
  phpmyadmin:
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
volumes:
  db:
networks:
  lamp-docker:
    driver: bridge
