version: "3"

#TODO
# come back and figure out how to configure apache2
# then i can push
services:
  web:
    restart: always
    image: php:8.1.23-apache
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    command: sh -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
  db:
    restart: always
    image: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db_script/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  db:
