version: "3"

services:
  web:
    restart: always
    image: php:8.1.23-apache
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  db:
    restart: always
    image: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db_script/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # this will be changed later once server is on server
      MYSQL_ROOT_PASSWORD: password
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
volumes:
  db:
networks:
  lamp-docker:
    driver: bridge
